#!/bin/bash

set -o errexit

usage ()
{
  echo "Usage: vpn-tunnel path/to/properties/file <connect|disconnect|reconnect|status>" 1>&2
  exit 0
}

msg ()
{
  echo $1
}

status ()
{
  pid=$(pgrep openconnect | tail -n 1)

  if [ ! -s "$pidfile" ]; then
    touch $pidfile
  fi

  vpn_pid=$(cat $pidfile)
  if [ ! $pid ]; then
    echo "VPN Tunnel $tunnelname is not active."
  elif [ $pid == $vpn_pid ]; then
     echo "VPN Tunnel $tunnelname is active and running with pid $pid"
     exit 0
  else
    echo "An unknown VPN Tunnel is active running with pid $pid"
    exit 0
  fi
}

connect ()
{
  # First check if a previous vpn instance is not running
  echo "Checking vpn connection status..."
  # sudo rm -f "$pidfile"
  status

  # Connect to VPN using openconnect (which supports Cisco AnyConnect protocol)
  echo "Creating VPN Tunnel..."
  #echo "$password" | sudo openconnect -b --script=$script --user=$username --pid-file=$pidfile --passwd-on-stdin $server $@ &> $logfile
  echo "$password" | sudo openconnect -b --script=$script --user=$username --pid-file=$pidfile --passwd-on-stdin $server
  #sudo openconnect -b --script=$script --user=$username --pid-file=$pidfile $server

  if [ ! -s "$pidfile" ]; then
      echo "ERROR: openconnect did not start successfully" 1>&2
      cat $logfile 1>&2
      # sudo rm -f "$pidfile"
      exit 1
  else
      echo "VPN Tunnel $tunnelname successfully created."
  fi
}

### Disconnect from the vpn server, or do not do anything if no vpn server has been started yet.
disconnect ()
{
  if [ ! -f "$pidfile" ]; then
    echo "No VPN Tunnel $tunnelname to disconnect."
  else
    pid="$(cat $pidfile)"
    sudo kill $pid
    echo "VPN Tunnel $tunnelname successfully disconnected."
    # sudo rm -f "$pidfile"
  fi
}

reconnect ()
{
  disconnect
  connect
}

[ "$#" -ne 2 ] && usage

source $1

[ -z ${tunnelname+x} ] && msg "tunnel name not specified in properties" && exit 0
[ -z ${script+x} ] && msg "script location not specified in properties" && exit 0 
[ -z ${username+x} ] && msg "username not specified in properties" && exit 0 
[ -z ${server+x} ] && msg "server not specified in properties" && exit 0 

pidfile="/tmp/$tunnelname.pid"
logfile="/tmp/$tunnelname.log"

touch $pidfile $logfile

case "$2" in
  status)
      status
      exit 0
      ;;
  connect)
      connect
      exit 0
      ;;
  disconnect)
      disconnect
      exit 0
      ;;
  reconnect)
      reconnect
      exit 0
      ;;
  *)
      usage
      exit 0
esac
