#!/bin/bash

((!$#)) && echo "usage: git archive-branch <git-branch-name>" && exit 1

#if git rev-parse --git-dir > /dev/null 2>&1; then
if [ -d .git ]; then
  : # This is a valid git repository (but the current working
    # directory may not be the top level.
    # Check the output of the git rev-parse command if you care)
    old_branch=$1
    #echo old branch: $branch_name

    new_branch=z_archive/${old_branch##*/}
    #echo new branch: $new_branch_name

    git branch -M $old_branch $new_branch
    git push origin $new_branch
    git push origin --delete $old_branch
else
  : # this is not a git repository
  echo "Current directory is not a valid git repo or you're not at the top level root directory of the repo."
fi

#http://stackoverflow.com/questions/4298960/git-add-a-git-commit-in-one-command
